on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
uses: gr2m/create-or-update-pull-request-action@v1
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
with:
  title: "Merge to env/test"
  body: "My pull request body"
  branch: "env/test"
  commit-message: "xxxxx"
